<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1584793331230' stop='1584793391157'>
    <name>Login to Application</name>
    <title>Login to Application</title>
    <test-cases>
        <test-case start='1584793331231' status='broken' stop='1584793391152'>
            <name>Login to application testcase</name>
            <title>Login to application testcase</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Alkesh\WebDriverIODemo\test\elements\homePage.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Alkesh\WebDriverIODemo\test\elements\homePage.js)
                    at Test.Runnable._timeoutError (C:\Users\Alkesh\WebDriverIO\node_modules\@wdio\mocha-framework\node_modules\mocha\lib\runnable.js:463:10)
                    at Timeout.&lt;anonymous> (C:\Users\Alkesh\WebDriverIO\node_modules\@wdio\mocha-framework\node_modules\mocha\lib\runnable.js:267:24)
                    at listOnTimeout (internal/timers.js:549:17)
                    at processTimers (internal/timers.js:492:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>